services:
  elasticsearch-service:
    image: elasticsearch:8.13.0
    container_name: client-calendar-elasticsearch
    healthcheck:
      start_period: 10s
      test: exit 0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ingest.geoip.downloader.enabled: 'false'
      discovery.type: 'single-node'
      ES_JAVA_OPTS: '-Xms256m -Xmx512m -XX:MaxDirectMemorySize=536870912'
      xpack.security.enabled: 'false' # This line disables security
